Added namespaces to all files
jochemste/sneakyengine pull request #11
Opened 2024-03-14 13:53 UTC by sopho-s

Haven't managed to get my compiler to work with this (really unsure why) but intellisense tells me it's fine (I wouldn't trust it but getting my compiler to work with this is a work in process 😢) if you want to compile it an check that would be great but I believe I haven't changed any code (hopefully)

2024-03-14 19:23 UTC, jochemste commented
Firstly, thanks for the effort you are putting in! I have resolved the merge conflicts here on Github (apparently that is also possible). The code still has some issues, which you can see from the Github Action that failed (this builds the code in a Docker container with a Ubuntu image). This most likely is related to changed calls to the code that is now in namespaces. Try to have a look and see if you can see what is going wrong. If you update this branch, make sure to first pull the new changes into your local branch. I will review the changes and leave comments where I might have some feedback.

2024-03-15 11:26 UTC, sopho-s commented
So the reason for this compilation error was due to me accidentally leaving a variable outside the namespace declaration

I would also like to ask, I'm trying to build with cmake (never used cmake before in my life) and I tried to run it and got this:

```Creating library C:/Users/nick/Documents/test/sneakyengine/_deps/sdl-build/Debug/SDL3.lib and ob
  ject C:/Users/nick/Documents/test/sneakyengine/_deps/sdl-build/Debug/SDL3.exp
  SDL3-shared.vcxproj -> C:\Users\nick\Documents\test\sneakyengine\bin\Debug\SDL3.dll
  Building Custom Rule C:/Users/nick/Documents/test/sneakyengine/src/logging/CMakeLists.txt
cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\nick\Documents\test\sneak
yengine\src\logging\logger.vcxproj]
  Building Custom Rule C:/Users/nick/Documents/test/sneakyengine/_deps/googletest-src/googlemock/CMak
  eLists.txt
cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\nick\Documents\test\sneak
yengine\_deps\googletest-build\googlemock\gmock.vcxproj]
  Building Custom Rule C:/Users/nick/Documents/test/sneakyengine/_deps/googletest-src/googlemock/CMak
  eLists.txt
cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\nick\Documents\test\sneak
yengine\_deps\googletest-build\googlemock\gmock_main.vcxproj]
  Building Custom Rule C:/Users/nick/Documents/test/sneakyengine/_deps/googletest-src/googletest/CMak
  eLists.txt
cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\nick\Documents\test\sneak
yengine\_deps\googletest-build\googletest\gtest.vcxproj]```

I searched it up and got [this](https://stackoverflow.com/questions/2274006/cmake-invalid-numeric-argument-wextra) but I don't want to edit any of the cmake files as I don't want to mess anything up

2024-03-17 17:02 UTC, jochemste commented
That is related to compiler options working for Linux, but not for Windows. I have not tried building this for Windows yet, only for Linux so far, but I would definitely want to add this, so this info is helpful. I will create a new issue for that and fix it soon, so you could hopefully build it locally as well. By the way, CMake is used very often, both in industry and open source projects, so a good skill to have.

As for the compilation errors, I see that there are more cases of references to variables in namespaces, like `LogLevel`.

2024-03-17 19:41 UTC, jochemste requested changes
Overall very nice work. I still have some comments about what can be changed, so have a look when you get the chance. In general I would prefer to have `impl` files/classes/directories out of the namespaces that are used externally. Otherwise this could be confusing, since anything with `impl` is only used inside the module, not outside. Let me know if I can help. Windows support is on the way, so that should make it easier

2024-03-17 19:41 UTC, jochemste commented on src/display/process_impl/display_proc_impl.cpp
> +  namespace display_process {
Thinking about how to call classes in this namespace (for example `display::display_process::DisplayProcessImpl()`) makes me feel like we could change this to have less repetition. So I would suggest to change `display_process` to `process`, so we can call `display::process::DisplayProcessImpl()`

2024-03-17 19:41 UTC, jochemste commented on src/display/process_impl/display_proc_impl.hpp
> +  namespace display_process {
Same here, I would suggest to change this to `process`

2024-03-17 19:41 UTC, jochemste commented on src/input/event/eventhandler_impl.cpp
> +  namespace event {
Same as with the other implementations, I do not think anything with `impl` in the filename/directoryname will need to be in the namespaces that are used externally (externally meaning outside of the module/submodule). Implementations are only referenced internally

2024-03-17 19:41 UTC, jochemste commented on src/input/event/eventhandler_impl.hpp
> +  namespace event {
Same for this implementation

2024-03-17 19:41 UTC, jochemste commented on src/input/process_input/event_proc.cpp
> +  namespace process_input {
same as with `display_process`, I would shorten this to `process`

2024-03-17 19:41 UTC, jochemste commented on src/input/process_input/event_proc.hpp
> +  namespace process_input {
process_input to process

2024-03-17 19:41 UTC, jochemste commented on src/logging/logging.hpp
> +  #define LOG_HEADER                \
I would prefer to keep these definitions outside of the namespace, they are used often and using the namespace with these makes things hard to read quickly.

2024-03-17 19:41 UTC, jochemste commented on src/process/process/libs/scheduler/scheduler.cpp
> +namespace process {
scheduler is a library to process, and should not be in the same namespace, so this namespace can be removed here.

2024-03-17 19:41 UTC, jochemste commented on src/process/process/libs/scheduler/scheduler.hpp
> +namespace process {
as mentioned in scheduler.cpp, I would prefer scheduler to not be in the process namespace

2024-03-17 19:41 UTC, jochemste commented on src/process/process/libs/threadpool/impl/default/threadpool_impl.cpp
> +namespace process {
Same as for scheduler, threadpool is a library and should not be in the process namespace

2024-03-19 19:41 UTC, jochemste commented
Windows build is now available. Have a look if you are able to try and compile

2024-03-21 00:07 UTC, sopho-s commented
@jochemste Apologies if I cannot do much for a few days, I am a bit busy currently, but I will back to it straight on Sunday 😄

2024-03-24 21:30 UTC, sopho-s commented
> Windows build is now available. Have a look if you are able to try and compile

I managed to get it working with your repository, I'll get the changes and pull it into my repo and try and fix the errors

2025-09-29 14:06 UTC, closed without merging